---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-2"
ratings:
  paths:
  - cli/**
  - lib/**
  - "**.js"
exclude_paths:
- coverage/**/*
- build/**/*
- "**/node_modules/**/*"
