sudo: false
language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

before_script:
- if (( "${TRAVIS_NODE_VERSION}" >= 6 )) && [ "$TRAVIS_BRANCH" = "master" ]; then export COVERAGE_REPORT=true; else echo $TRAVIS_NODE_VERSION; fi;
